global:
  resolve_timeout: 5m
  smtp_from: '{{ template "email.from" . }}'
  smtp_smarthost: 'smtp.exmail.qq.com:25'
  smtp_auth_username: 'xxxx@qq,com' # 不能使用 tmpl_string
  smtp_auth_password: 'password123456'
  smtp_require_tls: false

templates:
  - '/etc/alertmanager-tmpl/email.gohtml'

route:
  receiver: 'email'
  group_by: [ 'alertname' ]
  group_wait: 5s
  group_interval: 5s
  repeat_interval: 5m
  routes:
    - receiver: 'email'
      group_wait: 10s
      matchers:
        - severity="critical"

receivers: # 配置告警消息接受者信息，例如常用的 email、wechat、slack、webhook 等消息通知方式。
  - name: 'email'
    email_configs:
      - to: '{{ template "email.to" . }}'
        html: '{{ template "email.to.html" . }}'
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: [ 'alertname', 'instance' ]
