version: '2'
services:
  prometheus:
    image: registry.cn-hangzhou.aliyuncs.com/kennylee/prometheus:2.28.0
    container_name: prometheus
    restart: on-failure
    ports:
      - '9090:9090'
    volumes:
      - ./data:/opt/bitnami/prometheus/data:z
      - ./config/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '1'
